###################################################################################
# ⚠️ This file is controlled by OpenTofu in the estate-repos repository.
#    Manual changes will be overwritten the next time OpenTofu runs.
###################################################################################

name: todo-to-issue

on:
  workflow_dispatch:

jobs:
  call-todo-to-issue:
    uses: evoteum/estate-reusable-workflows/.github/workflows/todo-to-issue.yml@main